# Generated by Django 3.2.5 on 2021-07-31 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogs',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
