# Generated by Django 3.2.5 on 2021-08-04 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogs', '0002_alter_blogs_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='upvotes',
            field=models.ManyToManyField(related_name='blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
