# Generated by Django 3.2.5 on 2021-08-06 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogs', '0003_blogs_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='upvotes',
            field=models.ManyToManyField(related_name='upv', to=settings.AUTH_USER_MODEL),
        ),
    ]
