# Generated by Django 3.2.5 on 2021-08-08 17:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_alter_blogs_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogs',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=''),
        ),
    ]
