# Generated by Django 3.2.5 on 2021-08-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
